(()=>{'use strict';
const $=id=>document.getElementById(id),E={sp:$('spectrum'),wv:$('wave'),status:$('status'),statusText:$('statusText'),start:$('start'),record:$('record'),band:$('band'),db:$('db'),peak:$('peak'),bar:$('bar'),modes:$('modes'),threshold:$('threshold'),thresholdLabel:$('thresholdLabel'),sensitivity:$('sensitivity'),sensitivityLabel:$('sensitivityLabel'),sweepControl:$('sweepControl'),sweepSpeed:$('sweepSpeed'),sweepLabel:$('sweepLabel'),autoMark:$('autoMark'),monitor:$('monitor'),events:$('events'),mark:$('mark'),clear:$('clear'),downloads:$('downloads'),saveAudio:$('saveAudio'),saveLog:$('saveLog')};
let ac,stream,source,hp,lp,bp,analyser,gain,recorder,raf=0,running=false,recording=false,mode='voice',startAt=0,lastFrame=0,sweepPhase=0,prev=null,lastEvent=0,chunks=[],audioBlob=null,sessionDate=null,last={db:-Infinity,peak:NaN},events=[];
const sc=E.sp.getContext('2d'),wc=E.wv.getContext('2d');
function resize(c,x){const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=Math.floor(r.width*d);c.height=Math.floor(r.height*d);x.setTransform(d,0,0,d,0,0)}
function resizeAll(){resize(E.sp,sc);resize(E.wv,wc);idle()}addEventListener('resize',resizeAll);resizeAll();
function status(t,k=''){E.statusText.textContent=t;E.status.className='status'+(k?' '+k:'')}
function fmt(s){s=Math.max(0,s||0);return String(Math.floor(s/60)).padStart(2,'0')+':'+String(Math.floor(s%60)).padStart(2,'0')+'.'+Math.floor((s%1)*10)}
function tnow(){return running?(performance.now()-startAt)/1000:0}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function addEvent(type,db,peak,detail=''){const s=tnow();events.unshift({time:fmt(s),seconds:+s.toFixed(2),type,db:Number.isFinite(db)?+db.toFixed(1):null,peak:Number.isFinite(peak)?Math.round(peak):null,mode,detail});render();if(navigator.vibrate&&type!=='marcatore manuale')navigator.vibrate(20)}
function render(){E.events.innerHTML=events.length?events.map(e=>`<div class="event"><time>${e.time}</time><div><b>${esc(e.type)}</b><br><small>${e.db??'—'} dBFS · ${e.peak??'—'} Hz${e.detail?' · '+esc(e.detail):''}</small></div><span class="badge">${e.mode}</span></div>`).join(''):'<div class="empty">Nessun evento.</div>'}
function setMode(m){mode=m;[...E.modes.querySelectorAll('button')].forEach(b=>b.classList.toggle('active',b.dataset.mode===m));E.sweepControl.classList.toggle('hidden',m!=='sweep');applyFilters()}
[...E.modes.querySelectorAll('button[data-mode]')].forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));
E.threshold.oninput=()=>E.thresholdLabel.textContent=E.threshold.value+' dB';E.sensitivity.oninput=()=>E.sensitivityLabel.textContent=E.sensitivity.value+'%';E.sweepSpeed.oninput=()=>E.sweepLabel.textContent=(E.sweepSpeed.value/10).toFixed(1)+' s';
function applyFilters(){if(!ac)return;const t=ac.currentTime;if(mode==='voice'){hp.frequency.setTargetAtTime(300,t,.03);lp.frequency.setTargetAtTime(3400,t,.03);bp.type='peaking';bp.gain.setTargetAtTime(0,t,.03);E.band.innerHTML='300–3400 <small>Hz</small>'}else if(mode==='wide'){hp.frequency.setTargetAtTime(80,t,.03);lp.frequency.setTargetAtTime(Math.min(12000,ac.sampleRate/2-100),t,.03);bp.type='peaking';bp.gain.setTargetAtTime(0,t,.03);E.band.innerHTML='80–12000 <small>Hz</small>'}else{hp.frequency.setTargetAtTime(120,t,.03);lp.frequency.setTargetAtTime(Math.min(8000,ac.sampleRate/2-100),t,.03);bp.type='bandpass';bp.Q.setTargetAtTime(5,t,.03);E.band.innerHTML='250–5000 <small>Hz</small>'}}
E.monitor.onchange=()=>{if(gain&&ac)gain.gain.setTargetAtTime(E.monitor.checked?.75:0,ac.currentTime,.03)};
async function toggleMic(){if(running){await stopMic();return}try{if(!navigator.mediaDevices?.getUserMedia)throw Error('Microfono Web non disponibile. Serve Safari tramite HTTPS.');stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false,channelCount:1},video:false});ac=new(window.AudioContext||window.webkitAudioContext)();await ac.resume();source=ac.createMediaStreamSource(stream);hp=ac.createBiquadFilter();hp.type='highpass';lp=ac.createBiquadFilter();lp.type='lowpass';bp=ac.createBiquadFilter();analyser=ac.createAnalyser();analyser.fftSize=4096;analyser.smoothingTimeConstant=.55;analyser.minDecibels=-100;analyser.maxDecibels=-10;gain=ac.createGain();gain.gain.value=0;source.connect(hp);hp.connect(lp);lp.connect(bp);bp.connect(analyser);analyser.connect(gain);gain.connect(ac.destination);applyFilters();running=true;startAt=performance.now();lastFrame=startAt;sessionDate=new Date();prev=null;lastEvent=0;E.start.textContent='DISATTIVA MICROFONO';E.start.classList.add('stop');E.record.disabled=false;E.mark.disabled=false;status('MICROFONO ATTIVO','live');loop()}catch(err){status('ACCESSO NEGATO');alert('Impossibile attivare il microfono.\n\nApri la pagina in Safari tramite HTTPS e consenti il microfono.\n\n'+(err.message||err.name))}}
async function stopMic(){if(recording)await stopRecording();running=false;cancelAnimationFrame(raf);stream?.getTracks().forEach(t=>t.stop());try{await ac?.close()}catch{}stream=source=hp=lp=bp=analyser=gain=null;E.start.textContent='ATTIVA MICROFONO';E.start.classList.remove('stop');E.record.disabled=true;E.mark.disabled=true;E.monitor.checked=false;status('IN ATTESA');idle()}
function mime(){return['audio/mp4;codecs=mp4a.40.2','audio/mp4','audio/webm;codecs=opus','audio/webm'].find(t=>MediaRecorder.isTypeSupported?.(t))||''}
function startRecording(){if(!window.MediaRecorder){alert('Registrazione non disponibile in questa versione di Safari.');return}chunks=[];audioBlob=null;const m=mime();try{recorder=m?new MediaRecorder(stream,{mimeType:m}):new MediaRecorder(stream)}catch{recorder=new MediaRecorder(stream)}recorder.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};recorder.onstop=()=>{audioBlob=new Blob(chunks,{type:recorder.mimeType||m||'audio/mp4'});E.downloads.classList.remove('hidden')};recorder.start(500);recording=true;E.record.textContent='FERMA';E.record.classList.add('stop');status('REGISTRAZIONE','rec');addEvent('inizio registrazione',-Infinity,NaN)}
function stopRecording(){return new Promise(res=>{if(!recording||!recorder)return res();recorder.addEventListener('stop',res,{once:true});try{recorder.stop()}catch{res()}recording=false;E.record.textContent='REGISTRA';E.record.classList.remove('stop');status(running?'MICROFONO ATTIVO':'IN ATTESA',running?'live':'');addEvent('fine registrazione',-Infinity,NaN)})}
E.start.addEventListener('click',toggleMic);E.record.addEventListener('click',()=>recording?stopRecording():startRecording());E.mark.addEventListener('click',()=>addEvent('marcatore manuale',last.db,last.peak,'tocco utente'));E.clear.addEventListener('click',()=>{events=[];render()});
function save(blob,name){const a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1500)}
function stamp(){return new Date().toISOString().replace(/[:.]/g,'-').slice(0,19)}
E.saveAudio.addEventListener('click',()=>{if(audioBlob)save(audioBlob,'spirit-mic-'+stamp()+(audioBlob.type.includes('webm')?'.webm':'.m4a'))});
E.saveLog.addEventListener('click',()=>save(new Blob([JSON.stringify({app:'Spirit Mic',session_started_at:sessionDate?.toISOString()||null,note:'Eventi derivati da intensità e variazioni dello spettro del microfono.',settings:{mode,threshold_dbfs:+E.threshold.value,sensitivity_percent:+E.sensitivity.value},events:[...events].reverse()},null,2)],{type:'application/json'}),'spirit-mic-log-'+stamp()+'.json'));
function loop(now=performance.now()){if(!running||!analyser)return;const dt=Math.min(.1,(now-lastFrame)/1000);lastFrame=now;if(mode==='sweep'){const dur=+E.sweepSpeed.value/10;sweepPhase=(sweepPhase+dt/dur)%1;const center=250*Math.pow(20,(1-Math.cos(sweepPhase*Math.PI*2))/2);bp.frequency.setTargetAtTime(center,ac.currentTime,.025);E.band.innerHTML=Math.round(center)+' <small>Hz centro</small>'}
const f=new Float32Array(analyser.frequencyBinCount),tm=new Float32Array(analyser.fftSize);analyser.getFloatFrequencyData(f);analyser.getFloatTimeDomainData(tm);let sum=0;for(const v of tm)sum+=v*v;const rms=Math.sqrt(sum/tm.length),db=rms>0?20*Math.log10(rms):-Infinity;let pi=0,pd=-Infinity;for(let i=1;i<f.length;i++)if(f[i]>pd){pd=f[i];pi=i}const peak=pi*ac.sampleRate/analyser.fftSize;last={db,peak};let flux=0;if(prev){let n=0;for(let i=2;i<f.length;i+=3){flux+=Math.max(0,(f[i]||-100)-(prev[i]||-100));n++}flux/=n||1}prev=f.slice();const trig=db>+E.threshold.value&&flux>(1.2+(+E.sensitivity.value/100)*8.5);if(E.autoMark.checked&&trig&&performance.now()-lastEvent>1400){lastEvent=performance.now();addEvent('variazione audio',db,peak,'Δspettro '+flux.toFixed(1))}
drawSpectrum(f,peak);drawWave(tm);E.db.innerHTML=(Number.isFinite(db)?db.toFixed(1):'−∞')+' <small>dBFS</small>';E.peak.innerHTML=(Number.isFinite(peak)?Math.round(peak):'—')+' <small>Hz</small>';E.bar.style.width=Math.max(0,Math.min(100,((db+70)/60)*100))+'%';raf=requestAnimationFrame(loop)}
function drawSpectrum(a,peak){const w=E.sp.clientWidth,h=E.sp.clientHeight;sc.fillStyle='#03070a';sc.fillRect(0,0,w,h);sc.strokeStyle='#14273a';for(let i=1;i<5;i++){sc.beginPath();sc.moveTo(0,h*i/5);sc.lineTo(w,h*i/5);sc.stroke()}const maxHz=Math.min(mode==='voice'?5000:mode==='wide'?14000:8000,ac.sampleRate/2),maxI=Math.min(a.length-1,Math.floor(maxHz/(ac.sampleRate/analyser.fftSize))),g=sc.createLinearGradient(0,0,w,0);g.addColorStop(0,'#62e7ff');g.addColorStop(.65,'#69ffb4');g.addColorStop(1,'#ffc861');sc.strokeStyle=g;sc.lineWidth=2;sc.beginPath();for(let i=0;i<=maxI;i++){const x=i/maxI*w,y=h-Math.max(0,Math.min(1,(a[i]+100)/90))*h;i?sc.lineTo(x,y):sc.moveTo(x,y)}sc.stroke();const px=Math.min(w,peak/maxHz*w);sc.strokeStyle='#fff8';sc.setLineDash([4,5]);sc.beginPath();sc.moveTo(px,0);sc.lineTo(px,h);sc.stroke();sc.setLineDash([])}
function drawWave(a){const w=E.wv.clientWidth,h=E.wv.clientHeight;wc.fillStyle='#03070a';wc.fillRect(0,0,w,h);wc.strokeStyle='#183149';wc.beginPath();wc.moveTo(0,h/2);wc.lineTo(w,h/2);wc.stroke();wc.strokeStyle='#62e7ff';wc.lineWidth=1.5;wc.beginPath();const step=Math.max(1,Math.floor(a.length/w));let x=0;for(let i=0;i<a.length;i+=step){const y=h/2+a[i]*h*.45;x?wc.lineTo(x,y):wc.moveTo(x,y);x++}wc.stroke()}
function idle(){const w=E.sp.clientWidth,h=E.sp.clientHeight;sc.fillStyle='#03070a';sc.fillRect(0,0,w,h);sc.fillStyle='#647b91';sc.font='600 12px -apple-system';sc.textAlign='center';sc.fillText('ATTIVA IL MICROFONO PER INIZIARE',w/2,h/2);sc.textAlign='left';wc.fillStyle='#03070a';wc.fillRect(0,0,E.wv.clientWidth,E.wv.clientHeight);wc.strokeStyle='#183149';wc.beginPath();wc.moveTo(0,E.wv.clientHeight/2);wc.lineTo(E.wv.clientWidth,E.wv.clientHeight/2);wc.stroke();E.db.innerHTML='−∞ <small>dBFS</small>';E.peak.innerHTML='— <small>Hz</small>';E.bar.style.width='0'}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&running)addEvent('pagina in background',last.db,last.peak,'Safari può sospendere il microfono')});
})();
if('serviceWorker' in navigator){addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));}
