(()=>{'use strict';
const $=id=>document.getElementById(id);
const E={sp:$('spectrum'),wv:$('wave'),markerLayer:$('markerLayer'),status:$('status'),statusText:$('statusText'),elapsed:$('elapsed'),start:$('start'),record:$('record'),analysisState:$('analysisState'),db:$('db'),peak:$('peak'),bar:$('bar'),threshold:$('threshold'),thresholdLabel:$('thresholdLabel'),sensitivity:$('sensitivity'),sensitivityLabel:$('sensitivityLabel'),autoClip:$('autoClip'),monitor:$('monitor'),events:$('events'),mark:$('mark'),clear:$('clear'),downloads:$('downloads'),saveAudio:$('saveAudio'),saveLog:$('saveLog'),player:$('clipPlayer'),speechToggle:$('speechToggle'),speechSupport:$('speechSupport'),transcriptText:$('transcriptText'),transcriptMeta:$('transcriptMeta')};
let ac,stream,source,hp,lp,analyser,gain,processor,recorder,raf=0,wakeLock;
let running=false,sessionRecording=false,starting=false,startAt=0,lastFrame=0,lastTrigger=0,noiseFloor=-72;
let freqData,timeData,prevData,pcmRing=[],pcmRingSamples=0,pendingClip=null,sessionChunks=[],sessionBlob=null,events=[],markers=[],objectUrl=null,playerUrl=null,last={db:-Infinity,peak:NaN};
let recognition=null,speechRunning=false,transcriptFinal='';
const sc=E.sp.getContext('2d',{alpha:false}),wc=E.wv.getContext('2d',{alpha:false});
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}.${Math.floor((s%1)*10)}`;
const tnow=()=>running?(performance.now()-startAt)/1000:0;
function resize(c,x){const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=Math.max(1,Math.floor(r.width*d));c.height=Math.max(1,Math.floor(r.height*d));x.setTransform(d,0,0,d,0,0)}
function resizeAll(){resize(E.sp,sc);resize(E.wv,wc);clearCanvases()}addEventListener('resize',resizeAll,{passive:true});
function clearCanvases(){sc.fillStyle='#03070a';sc.fillRect(0,0,E.sp.clientWidth,E.sp.clientHeight);wc.fillStyle='#03070a';wc.fillRect(0,0,E.wv.clientWidth,E.wv.clientHeight);wc.strokeStyle='#183149';wc.beginPath();wc.moveTo(0,E.wv.clientHeight/2);wc.lineTo(E.wv.clientWidth,E.wv.clientHeight/2);wc.stroke()}resizeAll();
function setStatus(text,kind=''){E.statusText.textContent=text;E.status.className='status'+(kind?' '+kind:'')}
function supportedMime(){if(!window.MediaRecorder)return'';return['audio/mp4','audio/mp4;codecs=mp4a.40.2','audio/webm;codecs=opus','audio/webm'].find(t=>MediaRecorder.isTypeSupported?.(t))||''}
function addMarker(kind,label){const el=document.createElement('span');el.className='marker '+kind;el.dataset.label=label;E.markerLayer.appendChild(el);markers.push({el,x:E.sp.clientWidth-3});positionMarkers()}
function positionMarkers(dx=0){markers.forEach(m=>{m.x-=dx;m.el.style.left=m.x+'px'});markers=markers.filter(m=>{if(m.x<-90){m.el.remove();return false}return true})}
function addEvent(type,kind,score,db,peak,detail='',clip=null){const seconds=tnow(),ev={id:crypto.randomUUID?.()||String(Date.now()+Math.random()),time:fmt(seconds),seconds:+seconds.toFixed(2),type,kind,score:Math.round(score||0),db:Number.isFinite(db)?+db.toFixed(1):null,peak:Number.isFinite(peak)?Math.round(peak):null,detail,clip};events.unshift(ev);addMarker(kind,type==='Possibile voce'?'VOCE':type==='Evento sospetto EVP'?'EVP':'MARK');renderEvents();if(navigator.vibrate&&kind!=='manual')navigator.vibrate(18);return ev}
function renderEvents(){E.events.innerHTML=events.length?events.map(e=>`<div class="event"><time>${e.time}</time><div><b>${esc(e.type)}</b><br><small>${e.score?e.score+'% · ':''}${e.db??'—'} dBFS · ${e.peak??'—'} Hz${e.detail?' · '+esc(e.detail):''}</small></div><div class="event-actions"><span class="badge ${e.kind}">${e.clip?'WAV':'ATTESA'}</span>${e.clip?`<button data-play="${e.id}">ASCOLTA</button><button data-save="${e.id}">SALVA</button>`:''}</div></div>`).join(''):'<div class="empty">Nessun evento rilevato.</div>'}
E.events.addEventListener('click',async e=>{const p=e.target.closest('[data-play]'),s=e.target.closest('[data-save]');if(p){const ev=events.find(x=>x.id===p.dataset.play);if(ev?.clip){try{if(playerUrl)URL.revokeObjectURL(playerUrl);playerUrl=URL.createObjectURL(ev.clip);E.player.src=playerUrl;E.player.load();await E.player.play()}catch(err){alert('Safari non ha avviato la clip. Premi Play nel lettore audio sotto gli eventi.\n\n'+(err.message||''))}}}if(s){const ev=events.find(x=>x.id===s.dataset.save);if(ev?.clip)deliver(ev.clip,`evp-evento-${ev.time.replace(/[:.]/g,'-')}.wav`)}});
function reset(){pcmRing=[];pcmRingSamples=0;sessionChunks=[];events=[];markers.forEach(m=>m.el.remove());markers=[];pendingClip=null;sessionBlob=null;noiseFloor=-72;prevData=null;E.downloads.classList.add('hidden');renderEvents();clearCanvases();E.player.removeAttribute('src');E.player.load();if(playerUrl)URL.revokeObjectURL(playerUrl);playerUrl=null}
async function requestWake(){try{if('wakeLock'in navigator)wakeLock=await navigator.wakeLock.request('screen')}catch{}}
async function releaseWake(){try{await wakeLock?.release()}catch{}wakeLock=null}
async function toggleMic(){if(starting)return;if(running){await stopMic();return}starting=true;E.start.disabled=true;setStatus('RICHIESTA ACCESSO');try{if(!isSecureContext)throw Error('La pagina richiede HTTPS.');stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false,channelCount:1},video:false});const AC=window.AudioContext||window.webkitAudioContext;ac=new AC({latencyHint:'interactive'});await ac.resume();source=ac.createMediaStreamSource(stream);hp=ac.createBiquadFilter();hp.type='highpass';hp.frequency.value=70;lp=ac.createBiquadFilter();lp.type='lowpass';lp.frequency.value=Math.min(12000,ac.sampleRate/2-100);analyser=ac.createAnalyser();analyser.fftSize=4096;analyser.smoothingTimeConstant=.22;analyser.minDecibels=-115;analyser.maxDecibels=-20;gain=ac.createGain();gain.gain.value=0;processor=ac.createScriptProcessor(2048,1,1);source.connect(hp);hp.connect(lp);lp.connect(analyser);analyser.connect(gain);gain.connect(ac.destination);source.connect(processor);processor.connect(ac.destination);processor.onaudioprocess=capturePcm;freqData=new Float32Array(analyser.frequencyBinCount);timeData=new Float32Array(analyser.fftSize);startRecorder();reset();running=true;startAt=performance.now();lastFrame=startAt;E.start.textContent='DISATTIVA MICROFONO';E.start.classList.add('stop');E.record.disabled=false;E.mark.disabled=false;setStatus('ANALISI ATTIVA','live');await requestWake();loop()}catch(err){setStatus(err?.name==='NotAllowedError'?'PERMESSO NEGATO':'ERRORE');alert('Impossibile attivare il microfono.\n\nApri il sito in Safari tramite HTTPS e consenti il microfono.\n\n'+(err.message||err.name||'Errore sconosciuto'));await cleanup()}finally{starting=false;E.start.disabled=false}}
function capturePcm(e){if(!running)return;const src=e.inputBuffer.getChannelData(0),copy=new Float32Array(src);pcmRing.push(copy);pcmRingSamples+=copy.length;const max=Math.floor(ac.sampleRate*4);while(pcmRingSamples>max&&pcmRing.length){pcmRingSamples-=pcmRing[0].length;pcmRing.shift()}if(pendingClip){pendingClip.parts.push(copy);pendingClip.remaining-=copy.length;if(pendingClip.remaining<=0){const samples=mergeFloat32(pendingClip.parts);pendingClip.event.clip=encodeWav(samples,ac.sampleRate);pendingClip.event.detail+=' · clip pronta';pendingClip=null;renderEvents()}}}
function mergeFloat32(parts){const len=parts.reduce((n,p)=>n+p.length,0),out=new Float32Array(len);let o=0;for(const p of parts){out.set(p,o);o+=p.length}return out}
function encodeWav(samples,rate){const b=new ArrayBuffer(44+samples.length*2),v=new DataView(b);const str=(o,s)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i))};str(0,'RIFF');v.setUint32(4,36+samples.length*2,true);str(8,'WAVE');str(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,rate,true);v.setUint32(28,rate*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);str(36,'data');v.setUint32(40,samples.length*2,true);let o=44;for(let i=0;i<samples.length;i++,o+=2){const s=Math.max(-1,Math.min(1,samples[i]));v.setInt16(o,s<0?s*32768:s*32767,true)}return new Blob([b],{type:'audio/wav'})}
function startRecorder(){if(!window.MediaRecorder)return;const mime=supportedMime();recorder=mime?new MediaRecorder(stream,{mimeType:mime,audioBitsPerSecond:128000}):new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data?.size&&sessionRecording)sessionChunks.push(e.data)};recorder.start(1000)}
async function cleanup(){cancelAnimationFrame(raf);raf=0;stopSpeech();try{if(recorder?.state!=='inactive')recorder.stop()}catch{}if(processor)processor.onaudioprocess=null;stream?.getTracks().forEach(t=>t.stop());try{await ac?.close()}catch{}stream=source=hp=lp=analyser=gain=processor=ac=recorder=null;freqData=timeData=prevData=null;await releaseWake()}
async function stopMic(){if(sessionRecording)stopSessionRecording();running=false;await cleanup();E.start.textContent='ATTIVA MICROFONO';E.start.classList.remove('stop');E.record.disabled=true;E.mark.disabled=true;E.monitor.checked=false;E.elapsed.textContent='00:00.0';E.analysisState.textContent='—';setStatus('IN ATTESA');clearCanvases()}
function startSessionRecording(){if(!recorder){alert('Registrazione completa non disponibile in questo browser.');return}sessionChunks=[];sessionBlob=null;sessionRecording=true;E.record.textContent='FERMA SESSIONE';E.record.classList.add('stop');setStatus('REGISTRAZIONE','rec')}
function stopSessionRecording(){sessionRecording=false;sessionBlob=new Blob(sessionChunks,{type:recorder?.mimeType||'audio/mp4'});E.record.textContent='REGISTRA SESSIONE';E.record.classList.remove('stop');setStatus(running?'ANALISI ATTIVA':'IN ATTESA',running?'live':'');if(sessionBlob.size)E.downloads.classList.remove('hidden')}
function triggerAuto(kind,score,db,peak,detail){const type=kind==='anomaly'?'Evento sospetto EVP':'Possibile voce',ev=addEvent(type,kind,score,db,peak,detail);if(E.autoClip.checked&&!pendingClip)pendingClip={event:ev,parts:pcmRing.map(p=>new Float32Array(p)),remaining:Math.floor(ac.sampleRate*5)}}
E.start.addEventListener('click',toggleMic);E.record.addEventListener('click',()=>sessionRecording?stopSessionRecording():startSessionRecording());E.mark.addEventListener('click',()=>{const ev=addEvent('Marcatore manuale','manual',0,last.db,last.peak,'inserito dall’utente');if(E.autoClip.checked&&!pendingClip)pendingClip={event:ev,parts:pcmRing.map(p=>new Float32Array(p)),remaining:Math.floor(ac.sampleRate*5)}});E.clear.addEventListener('click',reset);
E.threshold.oninput=()=>E.thresholdLabel.textContent=E.threshold.value+' dB';E.sensitivity.oninput=()=>E.sensitivityLabel.textContent=E.sensitivity.value+'%';E.monitor.onchange=()=>{if(gain&&ac)gain.gain.setTargetAtTime(E.monitor.checked?.65:0,ac.currentTime,.03)};
function loop(now=performance.now()){if(!running||!analyser)return;if(ac.state==='suspended')ac.resume().catch(()=>{});const dt=Math.min(.1,(now-lastFrame)/1000);lastFrame=now;analyser.getFloatFrequencyData(freqData);analyser.getFloatTimeDomainData(timeData);let sum=0;for(const v of timeData)sum+=v*v;const rms=Math.sqrt(sum/timeData.length),db=rms>0?20*Math.log10(rms):-Infinity,hzPerBin=ac.sampleRate/analyser.fftSize;let peakDb=-Infinity,peakIndex=1,total=0,voice=0,low=0,high=0;for(let i=1;i<freqData.length;i++){const hz=i*hzPerBin,p=Math.pow(10,freqData[i]/10);total+=p;if(hz>=120&&hz<=3800)voice+=p;if(hz<120)low+=p;if(hz>5000)high+=p;if(freqData[i]>peakDb){peakDb=freqData[i];peakIndex=i}}const peak=peakDb>-102?peakIndex*hzPerBin:NaN;last={db,peak};if(Number.isFinite(db)&&db<+E.threshold.value)noiseFloor=noiseFloor*.985+db*.015;let flux=0,count=0;if(!prevData)prevData=new Float32Array(freqData.length);else for(let i=2;i<freqData.length;i+=3){flux+=Math.max(0,freqData[i]-prevData[i]);count++}prevData.set(freqData);flux/=count||1;const voiceRatio=total?voice/total:0,noisePenalty=total?(low+high)/total:1,adaptive=Math.max(+E.threshold.value,noiseFloor+6),levelScore=Math.max(0,Math.min(1,(db-adaptive)/20)),voiceScore=Math.max(0,Math.min(100,(voiceRatio*.76+levelScore*.42-noisePenalty*.16)*100)),fluxNorm=Math.max(0,Math.min(1,flux/7)),anomalyScore=Math.max(0,Math.min(100,(fluxNorm*.55+voiceRatio*.28+levelScore*.34-noisePenalty*.10)*100));const sensitivity=+E.sensitivity.value;let state='Ambiente';if(voiceScore>sensitivity&&db>adaptive)state='Possibile voce';if(anomalyScore>sensitivity+9&&flux>2&&db>adaptive)state='Evento anomalo';E.analysisState.textContent=state;const cooldown=4200;if(now-lastTrigger>cooldown){if(anomalyScore>sensitivity+11&&flux>2.2&&db>adaptive){lastTrigger=now;triggerAuto('anomaly',anomalyScore,db,peak,`variazione spettrale ${flux.toFixed(1)}`)}else if(voiceScore>sensitivity+4&&voiceRatio>.52&&db>adaptive){lastTrigger=now;triggerAuto('voice',voiceScore,db,peak,`energia vocale ${Math.round(voiceRatio*100)}%`)}}drawSpectrogram(freqData,dt);drawWave(timeData);E.elapsed.textContent=fmt(tnow());E.db.innerHTML=(Number.isFinite(db)?db.toFixed(1):'−∞')+' <small>dBFS</small>';E.peak.innerHTML=(Number.isFinite(peak)?Math.round(peak):'—')+' <small>Hz</small>';E.bar.style.width=Math.max(0,Math.min(100,((db+75)/60)*100))+'%';raf=requestAnimationFrame(loop)}
function heat(v,floor,ceil){const t=Math.max(0,Math.min(1,(v-floor)/(ceil-floor)));if(t<.18)return`rgb(1,${Math.round(8+t*90)},${Math.round(15+t*150)})`;if(t<.45)return`rgb(${Math.round(t*25)},${Math.round(35+t*260)},${Math.round(80+t*310)})`;if(t<.72)return`rgb(${Math.round(20+t*190)},${Math.round(120+t*150)},${Math.round(210-t*130)})`;return`rgb(${Math.round(120+t*135)},${Math.round(250-(t-.72)*500)},${Math.round(90-(t-.72)*250)})`}
function drawSpectrogram(a,dt){const w=E.sp.clientWidth,h=E.sp.clientHeight,dx=Math.max(1,Math.round(dt*35));sc.drawImage(E.sp,dx,0,w-dx,h,0,0,w-dx,h);const hzPerBin=ac.sampleRate/analyser.fftSize,minHz=70,maxHz=Math.min(8000,ac.sampleRate/2),floor=Math.max(-112,noiseFloor-22),ceil=Math.max(-58,noiseFloor+24);for(let y=0;y<h;y++){const frac=1-y/(h-1),hz=minHz*Math.pow(maxHz/minHz,frac),i=Math.min(a.length-1,Math.max(1,Math.round(hz/hzPerBin)));sc.fillStyle=heat(a[i],floor,ceil);sc.fillRect(w-dx,y,dx,1)}sc.fillStyle='#ffffff22';for(const hz of [100,300,1000,3000,8000]){if(hz>maxHz)continue;const y=h-(Math.log(hz/minHz)/Math.log(maxHz/minHz))*h;sc.fillRect(w-dx,y,dx,1)}positionMarkers(dx)}
function drawWave(a){const w=E.wv.clientWidth,h=E.wv.clientHeight;wc.fillStyle='#03070a';wc.fillRect(0,0,w,h);wc.strokeStyle='#183149';wc.beginPath();wc.moveTo(0,h/2);wc.lineTo(w,h/2);wc.stroke();wc.strokeStyle='#62dff4';wc.lineWidth=1.4;wc.beginPath();const step=Math.max(1,Math.floor(a.length/w));let x=0;for(let i=0;i<a.length;i+=step){const y=h/2+a[i]*h*.44;x?wc.lineTo(x,y):wc.moveTo(x,y);x++}wc.stroke()}
function setupSpeech(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){E.speechSupport.textContent='Riconoscimento parole non disponibile in questo Safari.';E.speechToggle.disabled=true;return}recognition=new SR();recognition.lang='it-IT';recognition.continuous=true;recognition.interimResults=true;recognition.maxAlternatives=3;E.speechSupport.textContent='Disponibile · richiede microfono attivo e può richiedere Internet.';E.speechToggle.disabled=false;recognition.onresult=e=>{let interim='',conf=[];for(let i=e.resultIndex;i<e.results.length;i++){const r=e.results[i],text=r[0]?.transcript?.trim()||'';if(r.isFinal){transcriptFinal+=(transcriptFinal?' ':'')+text;if(Number.isFinite(r[0]?.confidence))conf.push(Math.round(r[0].confidence*100))}else interim+=text+' '}E.transcriptText.textContent=(transcriptFinal+(interim?' · '+interim.trim():'')).trim()||'Nessuna trascrizione.';E.transcriptMeta.textContent=conf.length?`Confidenza browser: ${conf.join(', ')}% · risultato non conclusivo.`:'In ascolto: le parole provvisorie possono cambiare.'};recognition.onerror=e=>{E.transcriptMeta.textContent='Riconoscimento interrotto: '+e.error;stopSpeech()};recognition.onend=()=>{if(speechRunning&&running){try{recognition.start()}catch{}}else updateSpeechUi()}}
function updateSpeechUi(){E.speechToggle.textContent=speechRunning?'FERMA RICONOSCIMENTO PAROLE':'AVVIA RICONOSCIMENTO PAROLE';E.speechToggle.classList.toggle('stop',speechRunning)}
function startSpeech(){if(!recognition)return;if(!running){alert('Attiva prima il microfono.');return}transcriptFinal='';E.transcriptText.textContent='Ascolto in corso…';speechRunning=true;updateSpeechUi();try{recognition.start()}catch{}}
function stopSpeech(){if(!recognition)return;speechRunning=false;updateSpeechUi();try{recognition.stop()}catch{}}
E.speechToggle.addEventListener('click',()=>speechRunning?stopSpeech():startSpeech());setupSpeech();
function stamp(){return new Date().toISOString().replace(/[:.]/g,'-').slice(0,19)}
async function deliver(blob,name){if(!blob)return;const file=new File([blob],name,{type:blob.type||'application/octet-stream'});if(navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:name});return}catch(e){if(e.name==='AbortError')return}}if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(blob);const a=document.createElement('a');a.href=objectUrl;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>{URL.revokeObjectURL(objectUrl);objectUrl=null},10000)}
E.saveAudio.addEventListener('click',()=>sessionBlob&&deliver(sessionBlob,'evp-sessione-'+stamp()+(sessionBlob.type.includes('webm')?'.webm':'.m4a')));E.saveLog.addEventListener('click',()=>deliver(new Blob([JSON.stringify({app:'EVP Recorder Lab',version:'2.1',note:'Punteggi e trascrizioni indicano ipotesi acustiche, non origine paranormale.',transcript:E.transcriptText.textContent,settings:{threshold_dbfs:+E.threshold.value,sensitivity_percent:+E.sensitivity.value,automatic_clips:E.autoClip.checked},events:events.slice().reverse().map(({clip,...e})=>({...e,has_clip:!!clip}))},null,2)],{type:'application/json'}),'evp-log-'+stamp()+'.json'));
document.addEventListener('visibilitychange',async()=>{if(!document.hidden&&running){try{await ac?.resume();await requestWake()}catch{}}});addEventListener('pagehide',()=>running&&cleanup());
})();
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=2.1').catch(()=>{}));