function renderStudentSelect(){const sel=$('#studentSelect');const old=sel.value;sel.innerHTML=Object.keys(state.students).map(n=>`<option ${n===state.currentStudent?'selected':''}>${n}</option>`).join('');sel.onchange=()=>{state.currentStudent=sel.value;save();renderHome();renderTeacher()}}
function openProfiles(){go('teacher');setTimeout(()=>$('#newStudent').focus(),100)}
function addStudent(){const n=$('#newStudent').value.trim();if(!n){toast('Inserisci un nome.');return}if(state.students[n]){toast('Profilo già esistente.');return}state.students[n]={answered:0,correct:0,mistakes:[],byUnit:{},placement:null};state.currentStudent=n;$('#newStudent').value='';save();renderTeacher();toast('Profilo creato.')}
function deleteStudent(){const names=Object.keys(state.students);if(names.length===1){toast('Deve restare almeno un profilo.');return}if(!confirm(`Eliminare il profilo “${state.currentStudent}”?`))return;delete state.students[state.currentStudent];state.currentStudent=Object.keys(state.students)[0];save();renderTeacher()}
function applySettings(){state.settings={large:$('#largeText').checked,contrast:$('#highContrast').checked,dyslexia:$('#dyslexiaMode').checked,slowAudio:$('#slowAudio').checked};document.documentElement.style.setProperty('--base',state.settings.large?'19px':'16px');document.body.classList.toggle('contrast',state.settings.contrast);document.body.classList.toggle('dyslexia',state.settings.dyslexia);save()}
function loadSettings(){$('#largeText').checked=!!state.settings.large;$('#highContrast').checked=!!state.settings.contrast;$('#dyslexiaMode').checked=!!state.settings.dyslexia;$('#slowAudio').checked=!!state.settings.slowAudio;document.documentElement.style.setProperty('--base',state.settings.large?'19px':'16px');document.body.classList.toggle('contrast',state.settings.contrast);document.body.classList.toggle('dyslexia',state.settings.dyslexia)}
function renderTeacher(){const s=student();$('#statStudent').textContent=state.currentStudent;$('#statAnswers').textContent=s.answered;$('#statCorrect').textContent=s.correct;$('#statMistakes').textContent=s.mistakes.length;$('#statCustom').textContent=state.custom.length;$('#profileList').innerHTML=Object.keys(state.students).map(n=>`<button class="profile-tag" onclick="state.currentStudent='${esc(n)}';save();renderTeacher()">${n}${state.students[n].placement?' · '+state.students[n].placement.level:''}</button>`).join('');$('#customList').innerHTML=state.custom.length?'<h3>Esercizi personali</h3>'+state.custom.map(e=>`<div class="custom-item"><div><b>${unitName(e.unit)}</b><br>${e.prompt}</div><button class="btn danger small" onclick="deleteCustom('${e.id}')">Elimina</button></div>`).join(''):'<p class="hint">Nessun esercizio personale.</p>';loadSettings()}
function addCustomExercise(){const unit=$('#customUnit').value,type=$('#customType').value,prompt=$('#customPrompt').value.trim(),answer=$('#customAnswer').value.trim(),choices=$('#customChoices').value.split(';').map(s=>s.trim()).filter(Boolean);if(!prompt||!answer){toast('Inserisci domanda e risposta.');return}if(type==='choice'&&choices.length<2){toast('Inserisci almeno due opzioni.');return}if(type==='choice'&&!choices.some(c=>normalize(c)===normalize(answer)))choices.push(answer);state.custom.push({id:'custom-'+Date.now(),unit,type,prompt,answer,choices:type==='choice'?choices:undefined,hint:'Esercizio creato dalla docente.'});save();$('#customPrompt').value='';$('#customAnswer').value='';$('#customChoices').value='';renderTeacher();renderHome();toast('Esercizio aggiunto.')}
function deleteCustom(id){state.custom=state.custom.filter(e=>e.id!==id);Object.values(state.students).forEach(s=>s.mistakes=s.mistakes.filter(x=>x!==id));save();renderTeacher();renderHome()}
function updateStats(){const s=student();if($('#accuracyHome'))$('#accuracyHome').textContent=s.answered?Math.round(s.correct/s.answered*100)+'%':'—';if($('#mistakesHome'))$('#mistakesHome').textContent=s.mistakes.length}
function resetProgress(){if(!confirm('Azzerare i progressi dello studente selezionato?'))return;state.students[state.currentStudent]={answered:0,correct:0,mistakes:[],byUnit:{},placement:null};save();renderTeacher();toast('Progressi azzerati.')}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='italiano_insieme_v2_dati.json';a.click();URL.revokeObjectURL(a.href)}
function importData(ev){const f=ev.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!d.students||!d.currentStudent)throw 0;state=d;save();loadSettings();renderTeacher();renderHome();toast('Dati importati.')}catch{toast('File non valido.')}};r.readAsText(f);ev.target.value=''}
renderHome();renderLessonMenu();renderPracticeFilters();fillSelects();renderStudentSelect();startSession();buildFlash();renderFlashFilters();renderClassFilters();generateSheet();loadSettings();updateStats();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js').catch(()=>{});
