function renderFlashFilters(){$('#flashFilters').innerHTML=`<button class="chip ${flashUnit==='all'?'active':''}" onclick="setFlashUnit('all')">Tutte</button>`+units.map(u=>`<button class="chip ${flashUnit===u.id?'active':''}" onclick="setFlashUnit('${u.id}')">${u.num}</button>`).join('')}
function buildFlash(){flashDeck=units.filter(u=>flashUnit==='all'||u.id===flashUnit).flatMap(u=>u.vocab.map(v=>({word:v[0],meaning:v[1],unit:u.title})));flashIndex=0;flashFlipped=false}
function currentFlash(){return flashDeck[flashIndex]}
function renderFlash(){renderFlashFilters();if(!flashDeck.length)buildFlash();const f=currentFlash();$('#flashCounter').textContent=`${flashIndex+1} / ${flashDeck.length}`;$('#flashCard').classList.toggle('flipped',flashFlipped);$('#flashCard').innerHTML=f?`<div><div class="eyebrow">${f.unit}</div><div class="word">${flashFlipped?f.meaning:f.word}</div><div class="meaning">${flashFlipped?'Tocca per tornare alla parola':'Tocca per il significato'}</div></div>`:''}
function setFlashUnit(id){flashUnit=id;buildFlash();renderFlash()}
function flipFlash(){flashFlipped=!flashFlipped;renderFlash()}
function nextFlash(){flashIndex=(flashIndex+1)%flashDeck.length;flashFlipped=false;renderFlash()}
function prevFlash(){flashIndex=(flashIndex-1+flashDeck.length)%flashDeck.length;flashFlipped=false;renderFlash()}
function shuffleFlash(){flashDeck=shuffle(flashDeck);flashIndex=0;flashFlipped=false;renderFlash()}
function renderClassFilters(){$('#classFilters').innerHTML=`<button class="chip ${classUnit==='all'?'active':''}" onclick="setClassUnit('all')">Tutte</button>`+units.map(u=>`<button class="chip ${classUnit===u.id?'active':''}" onclick="setClassUnit('${u.id}')">${u.num}</button>`).join('')}
function renderClass(){renderClassFilters();if(!classQuestion)nextClassQuestion();const ans=classRevealed?`<div class="class-answer">${pretty(Array.isArray(classQuestion.answer)?classQuestion.answer[0]:classQuestion.answer)}</div>`:'';$('#classStage').innerHTML=`<div><div class="eyebrow">${unitName(classQuestion.unit)}</div><h2>${classQuestion.prompt}</h2>${ans}</div>`}
function setClassUnit(id){classUnit=id;nextClassQuestion()}
function nextClassQuestion(){const pool=exercises().filter(e=>classUnit==='all'||e.unit===classUnit);classQuestion=pool[Math.floor(Math.random()*pool.length)];classRevealed=false;renderClass()}
function revealClassAnswer(){classRevealed=true;renderClass()}
function fillSelects(){const opts=units.map(u=>`<option value="${u.id}">${u.num} · ${u.title}</option>`).join('');$('#sheetUnit').insertAdjacentHTML('beforeend',opts);$('#customUnit').innerHTML=opts}
function generateSheet(){const unit=$('#sheetUnit').value,count=Number($('#sheetCount').value),show=$('#sheetAnswers').value==='yes',title=$('#sheetTitle').value||'Ripasso di italiano',klass=$('#sheetClass').value||'',diff=$('#sheetDifficulty').value;const pool=shuffle(exercises().filter(e=>(unit==='all'||e.unit===unit)&&(diff==='all'||e.type===diff))).slice(0,count);const q=pool.map((e,i)=>{let ans='';if(e.type==='choice')ans=`<div>□ ${e.choices.join(' &nbsp;&nbsp; □ ')}</div>`;else if(e.type==='text')ans='<div class="blank"></div>';else ans=`<div style="margin:7px 0;color:#555">Parole: ${shuffle(e.tokens).join(' · ')}</div><div class="blank" style="min-width:75%"></div>`;return `<div class="sheet-q"><b>${i+1}. ${e.prompt}</b>${ans}</div>`}).join('');const key=show?`<div class="answer-key"><h3>Soluzioni</h3>${pool.map((e,i)=>`<div>${i+1}. ${pretty(Array.isArray(e.answer)?e.answer[0]:e.answer)}</div>`).join('')}</div>`:'';$('#printSheet').innerHTML=`<h2>${title}</h2><div class="sheet-meta"><span>Nome: __________________________</span><span>Data: ____________</span></div>${klass?`<p><b>Classe:</b> ${klass}</p>`:''}${q||'<p>Nessun esercizio corrisponde ai filtri.</p>'}${key}`}
