function renderPracticeFilters(){$('#practiceFilters').innerHTML=`<button class="chip ${selectedUnit==='all'?'active':''}" onclick="selectUnit('all')">Tutte</button>`+units.map(u=>`<button class="chip ${selectedUnit===u.id?'active':''}" onclick="selectUnit('${u.id}')">${u.num} · ${u.title}</button>`).join('')}
function selectUnit(id){selectedUnit=id;placementMode=false;$('#practiceTitle').textContent='Esercizi';renderPracticeFilters();startSession()}
function startSession(customList){placementMode=false;$('#practiceTitle').textContent='Esercizi';const pool=customList||exercises().filter(e=>selectedUnit==='all'||e.unit===selectedUnit);const n=Math.min(Number($('#sessionSize')?.value||10),pool.length);session=shuffle(pool).slice(0,n);current=0;sessionCorrect=0;answeredCurrent=false;orderAnswer=[];renderExercise()}
function startMistakes(){const pool=exercises().filter(e=>student().mistakes.includes(e.id));if(!pool.length){toast('Non ci sono errori da ripassare.');return}placementMode=false;session=shuffle(pool);current=0;sessionCorrect=0;go('practice');renderExercise()}
function startDaily(){const day=new Date().toISOString().slice(0,10);let seed=[...day].reduce((a,c)=>a+c.charCodeAt(0),0);const pool=exercises().filter(e=>selectedUnit==='all'||e.unit===selectedUnit);session=[...pool].sort((a,b)=>((a.id.charCodeAt(0)+seed)%97)-((b.id.charCodeAt(0)+seed)%97)).slice(0,5);current=0;sessionCorrect=0;placementMode=false;go('practice');renderExercise()}
function startPlacement(){placementMode=true;selectedUnit='all';session=[...placementExercises];current=0;sessionCorrect=0;answeredCurrent=false;orderAnswer=[];go('practice');$('#practiceTitle').textContent='Test iniziale';renderExercise()}
function renderExercise(){const card=$('#exerciseCard');if(!session.length){card.innerHTML='<div style="margin:auto;text-align:center"><h2>Nessun esercizio disponibile</h2></div>';updateProgress();return}if(current>=session.length){const pct=Math.round(sessionCorrect/session.length*100);if(placementMode){let level=pct<40?'A0 iniziale':pct<75?'A0 avanzato / avvio A1':'A1 iniziale';student().placement={score:pct,level,date:new Date().toLocaleDateString('it-IT')};save();card.innerHTML=`<div style="margin:auto;text-align:center;max-width:600px"><div class="iconbox" style="margin:0 auto 18px">?</div><div class="eyebrow">TEST COMPLETATO</div><h2>${sessionCorrect} su ${session.length}</h2><div class="placement-result"><b>Punto di partenza suggerito: ${level}</b><p>È un’indicazione didattica, non una certificazione ufficiale.</p></div><div class="actions" style="justify-content:center"><button class="btn primary" onclick="placementMode=false;startSession()">Inizia il percorso</button></div></div>`}else card.innerHTML=`<div style="margin:auto;text-align:center;max-width:520px"><div class="iconbox" style="margin:0 auto 18px">✓</div><div class="eyebrow">SESSIONE COMPLETATA</div><h2>${sessionCorrect} risposte corrette su ${session.length}</h2><p class="hint">Precisione: ${pct}%.</p><div class="actions" style="justify-content:center"><button class="btn ghost" onclick="startSession()">Nuova sessione</button><button class="btn primary" onclick="startMistakes()">Ripassa errori</button></div></div>`;updateProgress(true);return}const e=session[current],u=units.find(x=>x.id===e.unit)||units[0];answeredCurrent=false;orderAnswer=[];let body='';if(e.type==='choice')body=`<div class="options">${e.choices.map(c=>`<button class="option" onclick='selectChoice(this,${JSON.stringify(c)})'>${c}</button>`).join('')}</div>`;if(e.type==='text')body='<input class="answer-input" id="textAnswer" autocomplete="off" placeholder="Scrivi qui…" onkeydown="if(event.key===\'Enter\')checkAnswer()">';if(e.type==='order')body=`<div class="order-zone" id="orderAnswer"><span style="color:var(--muted)">La frase apparirà qui</span></div><div id="orderTokens" style="display:flex;flex-wrap:wrap;gap:9px">${shuffle(e.tokens).map(t=>`<button class="word-token" data-token="${t}" onclick="addToken(this)">${t}</button>`).join('')}</div>`;card.innerHTML=`<div class="exercise-meta"><span>${placementMode?'Test iniziale':'Unità '+u.num+' · '+u.title}</span><span>${current+1} di ${session.length}</span></div><h2>${e.prompt}</h2><div class="hint">${placementMode?'Scegli la risposta migliore.':e.hint||''}</div>${body}<div class="feedback" id="feedback"></div><div class="exercise-actions"><button class="btn ghost" onclick="speak('${esc(e.prompt)}')">🔊 Ascolta</button><div><button class="btn ghost" onclick="clearCurrent()">Cancella</button><button class="btn primary" id="checkBtn" onclick="checkAnswer()">Controlla</button></div></div>`;updateProgress()}
function selectChoice(btn,val){if(answeredCurrent)return;$$('.option').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');btn.dataset.value=val}
function addToken(btn){if(answeredCurrent)return;orderAnswer.push(btn.dataset.token);btn.disabled=true;btn.classList.add('in-answer');renderOrderAnswer()}
function renderOrderAnswer(){const z=$('#orderAnswer');if(!z)return;z.innerHTML=orderAnswer.map((t,i)=>`<button class="word-token in-answer" onclick="removeToken(${i})">${t}</button>`).join('')||'<span style="color:var(--muted)">La frase apparirà qui</span>'}
function removeToken(i){if(answeredCurrent)return;const token=orderAnswer[i];orderAnswer.splice(i,1);const btn=[...$$('#orderTokens .word-token')].find(b=>b.dataset.token===token&&b.disabled);if(btn){btn.disabled=false;btn.classList.remove('in-answer')}renderOrderAnswer()}
function clearCurrent(){if(answeredCurrent)return;const e=session[current];if(e.type==='choice')$$('.option').forEach(b=>b.classList.remove('selected'));if(e.type==='text')$('#textAnswer').value='';if(e.type==='order'){orderAnswer=[];$$('#orderTokens .word-token').forEach(b=>{b.disabled=false;b.classList.remove('in-answer')});renderOrderAnswer()}}
function getResponse(e){if(e.type==='choice')return $('.option.selected')?.textContent||'';if(e.type==='text')return $('#textAnswer')?.value||'';if(e.type==='order')return orderAnswer.join(' ');return''}
function isCorrect(e,r){const a=Array.isArray(e.answer)?e.answer:[e.answer];return a.some(x=>normalize(x)===normalize(r))}
function checkAnswer(){if(answeredCurrent){current++;renderExercise();return}const e=session[current],r=getResponse(e);if(!r){toast('Inserisci o seleziona una risposta.');return}const ok=isCorrect(e,r);answeredCurrent=true;sessionCorrect++;if(!ok)sessionCorrect--;if(!placementMode){const s=student();s.answered++;if(ok)s.correct++;s.byUnit[e.unit]=s.byUnit[e.unit]||{answered:0,correct:0};s.byUnit[e.unit].answered++;if(ok)s.byUnit[e.unit].correct++;if(ok)s.mistakes=s.mistakes.filter(id=>id!==e.id);else if(!s.mistakes.includes(e.id))s.mistakes.push(e.id);save()}const f=$('#feedback');f.className='feedback '+(ok?'good':'bad');f.innerHTML=ok?'✓ Risposta corretta.':`Risposta corretta: <b>${pretty(Array.isArray(e.answer)?e.answer[0]:e.answer)}</b>`;if(e.type==='choice')$$('.option').forEach(b=>{if(isCorrect(e,b.textContent))b.classList.add('correct');else if(b.classList.contains('selected'))b.classList.add('wrong')});$('#checkBtn').textContent=current===session.length-1?'Vedi risultato':'Prossimo';updateProgress()}
function updateProgress(done=false){const total=session.length||0,completed=done?total:current+(answeredCurrent?1:0);$('#progressBar').style.width=total?`${completed/total*100}%`:'0%';$('#progressLabel').textContent=`${completed} / ${total}`;$('#scoreLabel').textContent=`${sessionCorrect} corrette`}
