const units=window.units; const baseExercises=[...window.exercisesA,...window.exercisesB]; const placementExercises=window.placementExercises;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function storageGet(k){try{return window.localStorage.getItem(k)}catch{return null}}
function storageSet(k,v){try{window.localStorage.setItem(k,v)}catch{}}
const defaultState={currentStudent:'Classe',students:{Classe:{answered:0,correct:0,mistakes:[],byUnit:{},placement:null}},custom:[],settings:{large:false,contrast:false,dyslexia:false,slowAudio:false}};
let state=JSON.parse(storageGet('italianoInsiemeV2')||'null')||structuredClone(defaultState); if(!state.students||!Object.keys(state.students).length)state=structuredClone(defaultState); if(!state.settings)state.settings=defaultState.settings;
let selectedUnit='all',session=[],current=0,sessionCorrect=0,answeredCurrent=false,orderAnswer=[],placementMode=false;let flashUnit='all',flashDeck=[],flashIndex=0,flashFlipped=false;let classUnit='all',classQuestion=null,classRevealed=false;
function save(){storageSet('italianoInsiemeV2',JSON.stringify(state));updateStats();renderStudentSelect()}
function student(){return state.students[state.currentStudent]}
function exercises(){return [...baseExercises,...state.custom]}
function normalize(s){return String(s).toLowerCase().trim().replace(/[.,!?;:’']/g,'').replace(/\s+/g,' ')}
function pretty(v){return String(v).replace(/\s+([.,!?;:])/g,'$1').replace(/([’'])\s+/g,'$1')}
function shuffle(arr){return [...arr].sort(()=>Math.random()-.5)}
function unitName(id){return units.find(u=>u.id===id)?.title||id}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function go(view){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+view+'View').classList.add('active');$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'});if(view==='teacher')renderTeacher();if(view==='print')generateSheet();if(view==='flash')renderFlash();if(view==='class')renderClass()}
$$('.nav button').forEach(b=>b.onclick=()=>go(b.dataset.view));
function speak(text){if(!('speechSynthesis'in window)){toast('Lettura vocale non disponibile.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='it-IT';u.rate=state.settings.slowAudio?.68:.84;speechSynthesis.speak(u)}
function renderHome(){$('#homeUnits').innerHTML=units.map(u=>`<article class="unit-card"><div class="iconbox">${u.icon}</div><div class="eyebrow" style="color:${u.color}">UNITÀ ${u.num}</div><h3>${u.title}</h3><p>${u.subtitle}</p><button class="text-link" onclick="openLesson('${u.id}')">Esplora →</button></article>`).join('');$('#exerciseCountHome').textContent=exercises().length;updateStats()}
function renderLessonMenu(){$('#lessonMenu').innerHTML=units.map((u,i)=>`<button class="${i===0?'active':''}" onclick="renderLesson('${u.id}',this)"><b>Unità ${u.num}</b><br><small>${u.title}</small></button>`).join('');renderLesson(units[0].id)}
function esc(s){return String(s).replaceAll('\\','\\\\').replaceAll("'","\\'")}
function renderLesson(id,button){const u=units.find(x=>x.id===id);if(button){$$('#lessonMenu button').forEach(b=>b.classList.remove('active'));button.classList.add('active')}$('#lessonContent').innerHTML=`<div class="lesson-banner" style="background:linear-gradient(135deg,${u.color},#244657)"><div><div class="eyebrow">UNITÀ ${u.num}</div><h2>${u.title}</h2><p>${u.subtitle}</p></div><button class="speak" onclick="speak('${esc(u.title+'. '+u.subtitle)}')">🔊 Ascolta</button></div><div class="lesson-section"><h3>Obiettivi comunicativi</h3><div class="vocab-grid">${u.objectives.map(o=>`<div class="vocab"><b>✓ ${o}</b></div>`).join('')}</div></div><div class="lesson-section"><h3>Parole e frasi utili</h3><div class="vocab-grid">${u.vocab.map(v=>`<div class="vocab"><div><b>${v[0]}</b><small>${v[1]}</small></div><button class="mini-speak" onclick="speak('${esc(v[0])}')">🔊</button></div>`).join('')}</div></div><div class="lesson-section"><h3>Dialogo modello</h3><div class="dialogue">${u.dialogue.map(d=>`<div class="line"><span class="speaker">${d[0]}:</span> ${d[1]} <button class="mini-speak" onclick="speak('${esc(d[1])}')">🔊</button></div>`).join('')}</div></div><div class="actions"><button class="btn ghost" onclick="speak('${esc(u.dialogue.map(d=>d[1]).join(' '))}')">Ascolta tutto</button><button class="btn primary" onclick="selectedUnit='${u.id}';renderPracticeFilters();startSession();go('practice')">Esercizi dell’unità</button></div>`}
function openLesson(id){go('lessons');setTimeout(()=>{const i=units.findIndex(u=>u.id===id);renderLesson(id,$$('#lessonMenu button')[i])},10)}
